#!/usr/bin/env python3
"""
Collect teacher responses for SATBench prompt JSONL files with Hugging Face
Transformers. Designed for Princeton/Slurm array jobs.

Input by default:
    dataset/satbench_teacher_prompts.jsonl

Output by default:
    teacher_responses_qwen35_2b/records/row_00000.json
    teacher_responses_qwen35_2b/records/row_00001.json
    ...

Key features:
  * One output JSON per prompt row, written atomically.
  * Slurm-array sharding: 210 jobs * 10 rows = 2100 rows.
  * Resumption: within a shard, successful existing rows are skipped. Missing,
    corrupted, empty, error, or incomplete records are regenerated.
  * Combine mode: merges per-row JSON records into full JSONL and SFT JSONL.
  * Status mode: reports which rows are complete/incomplete/missing.

Typical full-run command inside a Slurm array task:
    python collect_qwen35_teacher_responses_resumable.py \
      --mode generate \
      --prompts dataset/satbench_teacher_prompts.jsonl \
      --output_dir teacher_responses_qwen35_2b \
      --model_id Qwen/Qwen3.5-2B \
      --local_files_only \
      --shard_idx ${SLURM_ARRAY_TASK_ID} \
      --shard_size 10
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
import traceback
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


# -----------------------------
# CLI
# -----------------------------

def env_int(name: str, default: Optional[int] = None) -> Optional[int]:
    val = os.environ.get(name)
    if val is None or val == "":
        return default
    try:
        return int(val)
    except ValueError:
        return default


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Collect Qwen teacher responses for SATBench prompts with resumable sharding."
    )

    parser.add_argument(
        "--mode",
        choices=["generate", "combine", "inspect", "status"],
        default="generate",
        help="generate: run inference; combine: merge row JSON files; inspect: preview prompt file; status: report missing/incomplete rows.",
    )

    # Input/output paths.
    parser.add_argument(
        "--prompts",
        type=str,
        default="dataset/satbench_teacher_prompts.jsonl",
        help="Path to prompt JSONL generated by generate_satbench_prompts_checked.py.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="teacher_responses_qwen35_2b",
        help="Output directory for per-row records and logs.",
    )
    parser.add_argument(
        "--combined_out",
        type=str,
        default="teacher_responses_qwen35_2b.jsonl",
        help="Output JSONL path used in --mode combine.",
    )
    parser.add_argument(
        "--sft_out",
        type=str,
        default="teacher_responses_qwen35_2b_sft.jsonl",
        help="Chat-style SFT JSONL path used in --mode combine.",
    )
    parser.add_argument(
        "--expected_rows",
        type=int,
        default=2100,
        help="Expected number of prompt rows. Use 0 to disable the check.",
    )

    # Sharding controls. By default, take shard_idx from SLURM_ARRAY_TASK_ID.
    parser.add_argument(
        "--shard_idx",
        type=int,
        default=env_int("SLURM_ARRAY_TASK_ID", 0),
        help="Zero-based shard index. Defaults to SLURM_ARRAY_TASK_ID when present.",
    )
    parser.add_argument(
        "--shard_size",
        type=int,
        default=10,
        help="Rows per shard. For 2100 rows and 210 jobs, use 10.",
    )
    parser.add_argument(
        "--start_idx",
        type=int,
        default=None,
        help="Optional inclusive start row. Overrides shard_idx/shard_size if set.",
    )
    parser.add_argument(
        "--end_idx",
        type=int,
        default=None,
        help="Optional exclusive end row. Overrides shard_idx/shard_size if set.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional maximum number of rows after sharding, useful for smoke tests.",
    )

    # Model/loading controls.
    parser.add_argument("--model_id", type=str, default="Qwen/Qwen3.5-2B")
    parser.add_argument(
        "--local_files_only",
        action="store_true",
        help="Load model/tokenizer only from the local Hugging Face cache.",
    )
    parser.add_argument(
        "--no_trust_remote_code",
        action="store_true",
        help="Pass trust_remote_code=False. Default is True.",
    )
    parser.add_argument(
        "--dtype",
        choices=["auto", "float16", "bfloat16", "float32"],
        default="auto",
        help="Use auto for mixed GPU types. Use float16 on V100 if auto has issues.",
    )
    parser.add_argument(
        "--device_map",
        type=str,
        default="auto",
        help="Use 'auto' for one GPU. Use 'cuda' to move the entire model to cuda:0 manually.",
    )
    parser.add_argument(
        "--attn_implementation",
        type=str,
        default=None,
        choices=["eager", "sdpa", "flash_attention_2"],
        help="Optional attention implementation passed to from_pretrained.",
    )

    # Prompt rendering controls.
    thinking = parser.add_mutually_exclusive_group()
    thinking.add_argument(
        "--enable_thinking",
        action="store_true",
        help="Try tokenizer.apply_chat_template(..., enable_thinking=True). Falls back if unsupported.",
    )
    thinking.add_argument(
        "--disable_thinking",
        action="store_true",
        help="Try tokenizer.apply_chat_template(..., enable_thinking=False). Falls back if unsupported.",
    )
    parser.add_argument(
        "--max_input_tokens",
        type=int,
        default=0,
        help="If >0, truncate tokenized input from the left to this length.",
    )

    # Generation controls.
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--max_new_tokens", type=int, default=2048)
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--top_p", type=float, default=0.95)
    parser.add_argument("--top_k", type=int, default=20)
    parser.add_argument("--repetition_penalty", type=float, default=1.05)
    parser.add_argument("--do_sample", action="store_true")
    parser.add_argument("--seed", type=int, default=1234)

    # Resumption/logging controls.
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Regenerate every row in the shard, even if a successful output already exists.",
    )
    parser.add_argument(
        "--skip_error_records",
        action="store_true",
        help="Treat existing error records as done. Default: retry error records.",
    )
    parser.add_argument(
        "--retry_truncated_records",
        action="store_true",
        help=(
            "Treat likely-truncated existing records as incomplete and regenerate them. "
            "Default: keep non-empty truncated responses as complete, because rerunning with "
            "the same max_new_tokens will usually truncate again."
        ),
    )
    parser.add_argument(
        "--skip_truncated_records",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "--save_error_records",
        action="store_true",
        help="Write error JSON files on failed rows. They are retried on resume unless --skip_error_records is set.",
    )
    parser.add_argument("--log_every", type=int, default=1)
    parser.add_argument("--save_prompt", action="store_true", default=True)
    parser.add_argument("--no_save_prompt", action="store_true")
    parser.add_argument(
        "--write_sft_all",
        action="store_true",
        help="In combine mode, include records with empty/error responses in the SFT file.",
    )

    args = parser.parse_args()
    if args.no_save_prompt:
        args.save_prompt = False
    args.trust_remote_code = not args.no_trust_remote_code
    # Backward compatibility with older Slurm commands that passed
    # --skip_truncated_records. In the checked version, skipping/trusting
    # non-empty truncated records is the default behavior.
    if getattr(args, "skip_truncated_records", False):
        args.retry_truncated_records = False
    return args


# -----------------------------
# Basic utilities
# -----------------------------

def eprint(*items: Any) -> None:
    print(*items, file=sys.stderr, flush=True)


def load_jsonl(path: str | Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            text = line.strip()
            if not text:
                continue
            try:
                obj = json.loads(text)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {line_no} of {path}: {exc}") from exc
            rows.append(obj)
    return rows


def atomic_write_json(path: str | Path, obj: Dict[str, Any]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
        f.write("\n")
    os.replace(tmp, path)


def output_path_for_index(output_dir: str | Path, index: int) -> Path:
    return Path(output_dir) / "records" / f"row_{index:05d}.json"


def shard_range(args: argparse.Namespace, n_rows: int) -> Tuple[int, int]:
    if args.start_idx is not None or args.end_idx is not None:
        start = 0 if args.start_idx is None else args.start_idx
        end = n_rows if args.end_idx is None else args.end_idx
    else:
        start = int(args.shard_idx) * int(args.shard_size)
        end = min(start + int(args.shard_size), n_rows)
    start = max(0, min(start, n_rows))
    end = max(start, min(end, n_rows))
    if args.limit is not None:
        end = min(end, start + args.limit)
    return start, end


def extract_final_label(text: str) -> Optional[str]:
    if not text:
        return None
    # Prefer bracketed final labels used in the prompt.
    matches = re.findall(r"\[\s*(SAT|UNSAT)\s*\]", text, flags=re.IGNORECASE)
    if matches:
        return matches[-1].upper()
    bare = re.findall(r"\b(UNSAT|SAT)\b", text, flags=re.IGNORECASE)
    if bare:
        return bare[-1].upper()
    return None


def normalize_label(label: Any) -> Optional[str]:
    if isinstance(label, bool):
        return "SAT" if label else "UNSAT"
    if label is None:
        return None
    s = str(label).strip().upper()
    if s in {"SAT", "TRUE", "SATISFIABLE"}:
        return "SAT"
    if s in {"UNSAT", "FALSE", "UNSATISFIABLE"}:
        return "UNSAT"
    return None


def get_ground_truth_label(row: Dict[str, Any]) -> Optional[str]:
    for key in ("label", "satisfiable"):
        if key in row:
            lab = normalize_label(row.get(key))
            if lab:
                return lab
    gt = row.get("ground_truth")
    if isinstance(gt, dict):
        for key in ("label", "satisfiable"):
            if key in gt:
                lab = normalize_label(gt.get(key))
                if lab:
                    return lab
    return None


def choose_torch_dtype(dtype_name: str):
    import torch
    if dtype_name == "auto":
        return "auto"
    if dtype_name == "float16":
        return torch.float16
    if dtype_name == "bfloat16":
        return torch.bfloat16
    if dtype_name == "float32":
        return torch.float32
    raise ValueError(f"Unsupported dtype: {dtype_name}")


def set_seed(seed: int) -> None:
    import random
    import numpy as np
    import torch
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def get_enable_thinking_value(args: argparse.Namespace) -> Optional[bool]:
    if args.enable_thinking:
        return True
    if args.disable_thinking:
        return False
    return None


# -----------------------------
# Resumption helpers
# -----------------------------

def read_json_if_possible(path: Path) -> Optional[Dict[str, Any]]:
    try:
        with open(path, "r", encoding="utf-8") as f:
            obj = json.load(f)
        return obj if isinstance(obj, dict) else None
    except Exception:
        return None


def is_successful_record(path: Path, args: argparse.Namespace) -> bool:
    """Return True iff this row should be skipped during resumption.

    By default, only non-error records with a non-empty teacher response are
    considered complete. Error records, corrupted files, and likely-truncated
    records are treated as pending so a rerun will retry them.
    """
    if not path.exists():
        return False
    rec = read_json_if_possible(path)
    if rec is None:
        return False
    if rec.get("error"):
        return bool(args.skip_error_records)
    response = rec.get("teacher_response")
    if not isinstance(response, str) or not response.strip():
        return False
    gen_info = rec.get("generation_info")
    if isinstance(gen_info, dict) and gen_info.get("likely_truncated_by_max_new_tokens"):
        return not bool(args.retry_truncated_records)
    return True


def pending_rows_for_range(
    rows: Sequence[Dict[str, Any]],
    start: int,
    end: int,
    args: argparse.Namespace,
) -> Tuple[List[Tuple[int, Dict[str, Any]]], List[int]]:
    selected = list(enumerate(rows[start:end], start=start))
    if args.overwrite:
        return selected, []
    pending: List[Tuple[int, Dict[str, Any]]] = []
    complete: List[int] = []
    for i, row in selected:
        path = output_path_for_index(args.output_dir, i)
        if is_successful_record(path, args):
            complete.append(i)
        else:
            pending.append((i, row))
    return pending, complete


# -----------------------------
# Prompt/model/generation
# -----------------------------

def render_prompt_from_messages(
    tokenizer: Any,
    messages: Sequence[Dict[str, str]],
    enable_thinking: Optional[bool],
) -> str:
    if hasattr(tokenizer, "apply_chat_template"):
        kwargs: Dict[str, Any] = {"tokenize": False, "add_generation_prompt": True}
        if enable_thinking is not None:
            kwargs["enable_thinking"] = enable_thinking
        try:
            return tokenizer.apply_chat_template(messages, **kwargs)
        except TypeError:
            kwargs.pop("enable_thinking", None)
            return tokenizer.apply_chat_template(messages, **kwargs)

    chunks: List[str] = []
    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        chunks.append(f"{role.upper()}:\n{content}")
    chunks.append("ASSISTANT:\n")
    return "\n\n".join(chunks)


def load_model_and_tokenizer(args: argparse.Namespace):
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    eprint(f"Loading tokenizer: {args.model_id}")
    tokenizer = AutoTokenizer.from_pretrained(
        args.model_id,
        trust_remote_code=args.trust_remote_code,
        local_files_only=args.local_files_only,
    )
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    model_kwargs: Dict[str, Any] = {
        "trust_remote_code": args.trust_remote_code,
        "local_files_only": args.local_files_only,
        "torch_dtype": choose_torch_dtype(args.dtype),
    }
    if args.device_map and args.device_map != "none" and args.device_map != "cuda":
        model_kwargs["device_map"] = args.device_map
    if args.attn_implementation:
        model_kwargs["attn_implementation"] = args.attn_implementation

    eprint(f"Loading model: {args.model_id}")
    model = AutoModelForCausalLM.from_pretrained(args.model_id, **model_kwargs)

    if args.device_map == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("--device_map cuda requested but CUDA is not available.")
        model = model.to("cuda")

    model.eval()
    return model, tokenizer


def get_model_device(model: Any):
    import torch
    if hasattr(model, "hf_device_map") and isinstance(model.hf_device_map, dict):
        for dev in model.hf_device_map.values():
            if dev not in ("cpu", "disk", "meta"):
                return torch.device(dev)
    try:
        return next(model.parameters()).device
    except StopIteration:
        return torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


def batch_iter(items: Sequence[Tuple[int, Dict[str, Any]]], batch_size: int) -> Iterable[List[Tuple[int, Dict[str, Any]]]]:
    for i in range(0, len(items), batch_size):
        yield list(items[i : i + batch_size])


def messages_from_row(row: Dict[str, Any]) -> List[Dict[str, str]]:
    messages = row.get("messages")
    if isinstance(messages, list) and messages:
        return messages
    fallback: List[Dict[str, str]] = []
    if row.get("system_prompt"):
        fallback.append({"role": "system", "content": str(row["system_prompt"])})
    fallback.append({"role": "user", "content": str(row.get("user_prompt", ""))})
    return fallback


def generate_for_batch(
    model: Any,
    tokenizer: Any,
    batch_rows: List[Tuple[int, Dict[str, Any]]],
    args: argparse.Namespace,
) -> List[Dict[str, Any]]:
    import torch

    enable_thinking = get_enable_thinking_value(args)
    prompts = [render_prompt_from_messages(tokenizer, messages_from_row(row), enable_thinking) for _, row in batch_rows]

    tok_kwargs: Dict[str, Any] = {"return_tensors": "pt", "padding": True}
    if args.max_input_tokens and args.max_input_tokens > 0:
        tok_kwargs.update({"truncation": True, "max_length": args.max_input_tokens})

    inputs = tokenizer(prompts, **tok_kwargs)
    input_token_counts = [int(x) for x in inputs["attention_mask"].sum(dim=1).tolist()]
    padded_input_len = int(inputs["input_ids"].shape[1])

    device = get_model_device(model)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    gen_kwargs: Dict[str, Any] = {
        "max_new_tokens": args.max_new_tokens,
        "do_sample": args.do_sample,
        "repetition_penalty": args.repetition_penalty,
        "pad_token_id": tokenizer.pad_token_id,
        "eos_token_id": tokenizer.eos_token_id,
    }
    if args.do_sample:
        gen_kwargs.update({"temperature": args.temperature, "top_p": args.top_p, "top_k": args.top_k})

    start_time = time.time()
    with torch.inference_mode():
        outputs = model.generate(**inputs, **gen_kwargs)
    elapsed = time.time() - start_time

    batch_generated_total = 0
    decoded: List[Tuple[str, int, bool]] = []
    for i in range(outputs.shape[0]):
        new_ids_tensor = outputs[i, padded_input_len:]
        gen_ids = [int(t) for t in new_ids_tensor.tolist() if int(t) != tokenizer.pad_token_id]
        response = tokenizer.decode(gen_ids, skip_special_tokens=True).strip()
        gen_token_count = len(gen_ids)
        batch_generated_total += gen_token_count
        ended_with_eos = bool(gen_ids and tokenizer.eos_token_id is not None and gen_ids[-1] == tokenizer.eos_token_id)
        likely_truncated = gen_token_count >= args.max_new_tokens and not ended_with_eos
        decoded.append((response, gen_token_count, likely_truncated))

    results: List[Dict[str, Any]] = []
    for i, (row_index, row) in enumerate(batch_rows):
        response, gen_token_count, likely_truncated = decoded[i]
        teacher_label = extract_final_label(response)
        gt_label = get_ground_truth_label(row)

        result: Dict[str, Any] = {
            "index": row.get("index", row_index),
            "row_index_in_prompt_file": row_index,
            "prompt_id": row.get("prompt_id", f"row_{row_index:05d}"),
            "model_id": args.model_id,
            "teacher_response": response,
            "teacher_extracted_label": teacher_label,
            "ground_truth_label": gt_label,
            "teacher_label_matches_ground_truth": (
                teacher_label == gt_label if teacher_label is not None and gt_label is not None else None
            ),
            "generation_info": {
                "input_tokens": input_token_counts[i],
                "generated_tokens": gen_token_count,
                "batch_elapsed_seconds": elapsed,
                "tokens_per_second_for_batch": batch_generated_total / elapsed if elapsed > 0 else None,
                "likely_truncated_by_max_new_tokens": likely_truncated,
                "max_new_tokens": args.max_new_tokens,
                "do_sample": args.do_sample,
                "temperature": args.temperature if args.do_sample else None,
                "top_p": args.top_p if args.do_sample else None,
                "top_k": args.top_k if args.do_sample else None,
                "repetition_penalty": args.repetition_penalty,
                "enable_thinking": enable_thinking,
            },
            "created_at_unix": time.time(),
            "slurm_job_id": os.environ.get("SLURM_JOB_ID"),
            "slurm_array_job_id": os.environ.get("SLURM_ARRAY_JOB_ID"),
            "slurm_array_task_id": os.environ.get("SLURM_ARRAY_TASK_ID"),
            "hostname": os.uname().nodename if hasattr(os, "uname") else None,
        }

        if args.save_prompt:
            result["messages"] = row.get("messages")
            result["system_prompt"] = row.get("system_prompt")
            result["user_prompt"] = row.get("user_prompt")
        for key in ["label", "satisfiable", "certificate_type", "ground_truth"]:
            if key in row:
                result[key] = row[key]

        results.append(result)

    return results


# -----------------------------
# Modes
# -----------------------------

def prepare_output_dirs(output_dir: str | Path) -> None:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    (Path(output_dir) / "records").mkdir(parents=True, exist_ok=True)
    (Path(output_dir) / "logs").mkdir(parents=True, exist_ok=True)


def run_generate(args: argparse.Namespace) -> None:
    import torch

    prepare_output_dirs(args.output_dir)
    rows = load_jsonl(args.prompts)
    if args.expected_rows and len(rows) != args.expected_rows:
        raise ValueError(f"Expected {args.expected_rows} prompt rows, found {len(rows)} in {args.prompts}")

    n_rows = len(rows)
    start, end = shard_range(args, n_rows)
    pending, complete = pending_rows_for_range(rows, start, end, args)

    eprint(f"Loaded {n_rows} prompt rows from {args.prompts}")
    eprint(f"Shard idx={args.shard_idx}, shard_size={args.shard_size}; sub-range=[{start}, {end})")
    eprint(f"Resume scan: complete={len(complete)}, pending={len(pending)}, pending_rows={[i for i, _ in pending]}")

    shard_meta = {
        "model_id": args.model_id,
        "prompts": args.prompts,
        "output_dir": args.output_dir,
        "shard_idx": args.shard_idx,
        "shard_size": args.shard_size,
        "start": start,
        "end": end,
        "complete_rows_at_start": complete,
        "pending_rows_at_start": [i for i, _ in pending],
        "batch_size": args.batch_size,
        "max_new_tokens": args.max_new_tokens,
        "dtype": args.dtype,
        "device_map": args.device_map,
        "local_files_only": args.local_files_only,
        "slurm_job_id": os.environ.get("SLURM_JOB_ID"),
        "slurm_array_job_id": os.environ.get("SLURM_ARRAY_JOB_ID"),
        "slurm_array_task_id": os.environ.get("SLURM_ARRAY_TASK_ID"),
        "cuda_visible_devices": os.environ.get("CUDA_VISIBLE_DEVICES"),
        "hostname": os.uname().nodename if hasattr(os, "uname") else None,
    }
    atomic_write_json(Path(args.output_dir) / "logs" / f"shard_{int(args.shard_idx):05d}_meta.json", shard_meta)

    if not pending:
        eprint("Nothing to do for this shard. All rows are already complete.")
        return

    set_seed(args.seed + int(args.shard_idx))
    load_start = time.time()
    model, tokenizer = load_model_and_tokenizer(args)
    load_elapsed = time.time() - load_start
    eprint(f"Model loaded in {load_elapsed:.2f} seconds")

    total_generated = 0
    total_prompt_tokens = 0
    done = 0
    failures = 0
    gen_start = time.time()

    for batch in batch_iter(pending, max(1, args.batch_size)):
        try:
            results = generate_for_batch(model, tokenizer, batch, args)
        except Exception as exc:
            failures += len(batch)
            err = "".join(traceback.format_exception(type(exc), exc, exc.__traceback__))
            eprint(f"ERROR while generating batch rows {[i for i, _ in batch]}:\n{err}")
            if args.save_error_records:
                for row_index, row in batch:
                    error_record = {
                        "index": row.get("index", row_index),
                        "row_index_in_prompt_file": row_index,
                        "prompt_id": row.get("prompt_id", f"row_{row_index:05d}"),
                        "model_id": args.model_id,
                        "error": str(exc),
                        "traceback": err,
                        "created_at_unix": time.time(),
                        "slurm_job_id": os.environ.get("SLURM_JOB_ID"),
                        "slurm_array_task_id": os.environ.get("SLURM_ARRAY_TASK_ID"),
                    }
                    if args.save_prompt:
                        error_record["messages"] = row.get("messages")
                    atomic_write_json(output_path_for_index(args.output_dir, row_index), error_record)
            continue

        for result in results:
            row_index = int(result["row_index_in_prompt_file"])
            atomic_write_json(output_path_for_index(args.output_dir, row_index), result)
            total_generated += int(result["generation_info"].get("generated_tokens") or 0)
            total_prompt_tokens += int(result["generation_info"].get("input_tokens") or 0)
            done += 1
            eprint(f"Wrote row {row_index} -> {output_path_for_index(args.output_dir, row_index)}")

        if done % max(1, args.log_every) == 0 or done == len(pending):
            elapsed = time.time() - gen_start
            tok_s = total_generated / elapsed if elapsed > 0 else 0.0
            eprint(f"Progress shard {args.shard_idx}: newly_completed={done}/{len(pending)}, failures={failures}, gen_tok/s={tok_s:.2f}")
            if torch.cuda.is_available():
                try:
                    eprint(
                        f"CUDA max allocated={torch.cuda.max_memory_allocated()/(1024**3):.2f} GiB, "
                        f"max reserved={torch.cuda.max_memory_reserved()/(1024**3):.2f} GiB"
                    )
                except Exception:
                    pass

    total_elapsed = time.time() - gen_start
    # Re-scan at the end so the summary reflects resumable state.
    pending_after, complete_after = pending_rows_for_range(rows, start, end, args)
    summary = {
        "model_id": args.model_id,
        "prompts": args.prompts,
        "output_dir": args.output_dir,
        "shard_idx": args.shard_idx,
        "shard_size": args.shard_size,
        "start": start,
        "end": end,
        "rows_completed_this_run": done,
        "failures_this_run": failures,
        "complete_rows_after_run": complete_after,
        "pending_rows_after_run": [i for i, _ in pending_after],
        "total_generated_tokens_this_run": total_generated,
        "total_prompt_tokens_this_run": total_prompt_tokens,
        "load_seconds": load_elapsed,
        "generation_seconds": total_elapsed,
        "generated_tokens_per_second": total_generated / total_elapsed if total_elapsed > 0 else None,
        "rows_per_hour": done / total_elapsed * 3600 if total_elapsed > 0 else None,
        "slurm_job_id": os.environ.get("SLURM_JOB_ID"),
        "slurm_array_job_id": os.environ.get("SLURM_ARRAY_JOB_ID"),
        "slurm_array_task_id": os.environ.get("SLURM_ARRAY_TASK_ID"),
        "cuda_visible_devices": os.environ.get("CUDA_VISIBLE_DEVICES"),
        "hostname": os.uname().nodename if hasattr(os, "uname") else None,
    }
    atomic_write_json(Path(args.output_dir) / "logs" / f"shard_{int(args.shard_idx):05d}_summary.json", summary)
    eprint("SUMMARY " + json.dumps(summary, ensure_ascii=False))


def run_inspect(args: argparse.Namespace) -> None:
    rows = load_jsonl(args.prompts)
    print(f"Loaded {len(rows)} rows from {args.prompts}")
    if args.expected_rows and len(rows) != args.expected_rows:
        print(f"WARNING: expected {args.expected_rows} rows")
    if not rows:
        return
    first = rows[0]
    print("First row keys:", sorted(first.keys()))
    print("First row prompt_id:", first.get("prompt_id"))
    print("First row label:", first.get("label"))
    messages = first.get("messages")
    if isinstance(messages, list):
        print("messages roles:", [m.get("role") for m in messages])
        for m in messages:
            role = m.get("role")
            content = str(m.get("content", ""))
            print(f"--- {role} content preview ---")
            print(content[:1200])
            print()


def iter_record_files(output_dir: str | Path) -> Iterable[Path]:
    records_dir = Path(output_dir) / "records"
    if not records_dir.exists():
        return []
    return sorted(records_dir.glob("row_*.json"))


def run_status(args: argparse.Namespace) -> None:
    rows = load_jsonl(args.prompts)
    if args.expected_rows and len(rows) != args.expected_rows:
        print(f"WARNING: expected {args.expected_rows} prompt rows, found {len(rows)}")
    complete: List[int] = []
    missing_or_incomplete: List[int] = []
    errors: List[int] = []
    truncated: List[int] = []
    for i in range(len(rows)):
        path = output_path_for_index(args.output_dir, i)
        rec = read_json_if_possible(path)
        if rec is None:
            missing_or_incomplete.append(i)
            continue
        if rec.get("error"):
            errors.append(i)
            if not args.skip_error_records:
                missing_or_incomplete.append(i)
            else:
                complete.append(i)
            continue
        gen = rec.get("generation_info")
        if isinstance(gen, dict) and gen.get("likely_truncated_by_max_new_tokens"):
            truncated.append(i)
            if args.retry_truncated_records:
                missing_or_incomplete.append(i)
            else:
                complete.append(i)
            continue
        if isinstance(rec.get("teacher_response"), str) and rec["teacher_response"].strip():
            complete.append(i)
        else:
            missing_or_incomplete.append(i)

    summary = {
        "prompts": args.prompts,
        "output_dir": args.output_dir,
        "n_prompt_rows": len(rows),
        "n_complete": len(complete),
        "n_missing_or_incomplete": len(missing_or_incomplete),
        "n_error_records": len(errors),
        "n_likely_truncated_records": len(truncated),
        "first_missing_or_incomplete": missing_or_incomplete[:50],
        "first_error_records": errors[:50],
        "first_truncated_records": truncated[:50],
    }
    print("STATUS " + json.dumps(summary, ensure_ascii=False, indent=2))


def run_combine(args: argparse.Namespace) -> None:
    files = list(iter_record_files(args.output_dir))
    if not files:
        raise FileNotFoundError(f"No row_*.json files found under {Path(args.output_dir) / 'records'}")

    records: List[Dict[str, Any]] = []
    errors = 0
    for p in files:
        rec = read_json_if_possible(p)
        if rec is None:
            errors += 1
            continue
        if rec.get("error"):
            errors += 1
        records.append(rec)

    records.sort(key=lambda r: int(r.get("row_index_in_prompt_file", r.get("index", 10**12))))

    combined_path = Path(args.combined_out)
    if combined_path.parent != Path("."):
        combined_path.parent.mkdir(parents=True, exist_ok=True)
    with open(combined_path, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    sft_path = Path(args.sft_out)
    if sft_path.parent != Path("."):
        sft_path.parent.mkdir(parents=True, exist_ok=True)
    sft_count = 0
    with open(sft_path, "w", encoding="utf-8") as f:
        for rec in records:
            response = rec.get("teacher_response")
            if not response and not args.write_sft_all:
                continue
            messages = rec.get("messages")
            if not isinstance(messages, list):
                continue
            sft_obj = {
                "prompt_id": rec.get("prompt_id"),
                "index": rec.get("index"),
                "row_index_in_prompt_file": rec.get("row_index_in_prompt_file"),
                "model_id": rec.get("model_id"),
                "ground_truth_label": rec.get("ground_truth_label"),
                "teacher_extracted_label": rec.get("teacher_extracted_label"),
                "teacher_label_matches_ground_truth": rec.get("teacher_label_matches_ground_truth"),
                "messages": messages + [{"role": "assistant", "content": response or ""}],
            }
            if "ground_truth" in rec:
                sft_obj["ground_truth"] = rec["ground_truth"]
            f.write(json.dumps(sft_obj, ensure_ascii=False) + "\n")
            sft_count += 1

    summary = {
        "output_dir": args.output_dir,
        "n_record_files_read": len(files),
        "n_records_written": len(records),
        "n_error_or_corrupted_records": errors,
        "combined_out": str(combined_path),
        "sft_out": str(sft_path),
        "n_sft_rows": sft_count,
    }
    print("COMBINE_SUMMARY " + json.dumps(summary, ensure_ascii=False, indent=2))


def main() -> None:
    args = parse_args()
    if args.mode == "inspect":
        run_inspect(args)
    elif args.mode == "status":
        run_status(args)
    elif args.mode == "combine":
        run_combine(args)
    elif args.mode == "generate":
        run_generate(args)
    else:
        raise ValueError(args.mode)


if __name__ == "__main__":
    main()
